#link for the game of Reeborg's : https://reeborg.ca/reeborg.html?lang=en&mode=python&menu=worlds%2Fmenus%2Freeborg_intro_en.json&name=Alone&url=worlds%2Ftutorial_en%2Falone.json
#link learn : https://reeborg.ca/docs/en/basics/move.html
def left_around():
    turn_left()
    turn_left()
    turn_left()
    turn_left()
def right_around():
    turn_left()
    turn_left()
    turn_left()
turn_left()
move()
right_around()
move()
right_around()
move()
right_around()
move()
#move()
#move()
#left_around()
#move()
#move()
#left_around()
#move()
#move()

#Part 2 GAME 
def left_around():
    turn_left()
    turn_left()
    turn_left()
    turn_left()
def right_around():
    turn_left()
    turn_left()
    turn_left()
def game():
    turn_left()
    move()
    right_around()
    move()
    right_around()
    move()
    right_around()
    move()
    right_around()
    move()
    move()
    left_around()
    move()
move()
left_around()
move()
move()
turn_left()
move()
right_around()
move()
right_around()
move()
right_around()
move()
right_around()
move()
move()
left_around()
move()
move()
left_around()
move()
move()
game()
